-- Phase 3 schema update: add subscription and payment tracking.
-- Safe to run multiple times.

BEGIN;

CREATE TABLE IF NOT EXISTS "Subscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Tier" varchar(20) NOT NULL DEFAULT 'free',
    "BillingPeriod" varchar(20) NOT NULL DEFAULT 'monthly',
    "PaymentStatus" varchar(20) NOT NULL DEFAULT 'pending',
    "Amount" numeric(12,2) NOT NULL DEFAULT 0,
    "Currency" varchar(10) NOT NULL DEFAULT 'VND',
    "PaymentProvider" varchar(50) NULL,
    "PaymentTransactionCode" varchar(120) NULL,
    "PaidUtc" timestamptz NULL,
    "StartedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "ExpiresUtc" timestamptz NOT NULL,
    "CreatedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "UpdatedUtc" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Subscriptions_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Subscriptions_UserId_ExpiresUtc"
    ON "Subscriptions" ("UserId", "ExpiresUtc");

CREATE INDEX IF NOT EXISTS "IX_Subscriptions_UserId_PaymentStatus_ExpiresUtc"
    ON "Subscriptions" ("UserId", "PaymentStatus", "ExpiresUtc");

COMMIT;
