-- Phase 3 schema update: add subscription and payment tracking.
-- Safe to run multiple times.

BEGIN;

CREATE TABLE IF NOT EXISTS "Subscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Tier" varchar(20) NOT NULL DEFAULT 'free',
    "BillingPeriod" varchar(20) NOT NULL DEFAULT 'monthly',
    "PaymentStatus" varchar(20) NOT NULL DEFAULT 'pending',
    "Amount" numeric(12,2) NOT NULL DEFAULT 0,
    "Currency" varchar(10) NOT NULL DEFAULT 'VND',
    "PaymentProvider" varchar(50) NULL,
    "PaymentTransactionCode" varchar(120) NULL,
    "PaidUtc" timestamptz NULL,
    "StartedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "ExpiresUtc" timestamptz NOT NULL,
    "CreatedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "UpdatedUtc" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Subscriptions_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Subscriptions_UserId_ExpiresUtc"
    ON "Subscriptions" ("UserId", "ExpiresUtc");

CREATE INDEX IF NOT EXISTS "IX_Subscriptions_UserId_PaymentStatus_ExpiresUtc"
    ON "Subscriptions" ("UserId", "PaymentStatus", "ExpiresUtc");

CREATE TABLE IF NOT EXISTS "SubscriptionPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PlanCode" varchar(40) NOT NULL,
    "DisplayName" varchar(120) NOT NULL,
    "Tier" varchar(20) NOT NULL,
    "BillingPeriod" varchar(20) NOT NULL,
    "FixedPrice" numeric(12,2) NOT NULL DEFAULT 0,
    "Currency" varchar(10) NOT NULL DEFAULT 'VND',
    "MaxAccessiblePoiCount" integer NULL,
    "MaxOwnerPoiCount" integer NULL,
    "MaxActivationRadiusMeters" integer NOT NULL DEFAULT 150,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "UpdatedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "CreatedByAdminUserId" integer NOT NULL,
    "UpdatedByAdminUserId" integer NULL,
    CONSTRAINT "FK_SubscriptionPlans_Users_CreatedByAdminUserId"
        FOREIGN KEY ("CreatedByAdminUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SubscriptionPlans_Users_UpdatedByAdminUserId"
        FOREIGN KEY ("UpdatedByAdminUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_SubscriptionPlans_PlanCode"
    ON "SubscriptionPlans" ("PlanCode");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_SubscriptionPlans_Tier_BillingPeriod"
    ON "SubscriptionPlans" ("Tier", "BillingPeriod");

CREATE INDEX IF NOT EXISTS "IX_SubscriptionPlans_IsActive"
    ON "SubscriptionPlans" ("IsActive");

CREATE TABLE IF NOT EXISTS "PaymentTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "SubscriptionId" integer NULL,
    "PaymentProvider" varchar(30) NOT NULL DEFAULT 'manual',
    "PaymentStatus" varchar(20) NOT NULL DEFAULT 'pending',
    "TransactionCode" varchar(120) NOT NULL,
    "ProviderReferenceCode" varchar(120) NULL,
    "Amount" numeric(12,2) NOT NULL DEFAULT 0,
    "Currency" varchar(10) NOT NULL DEFAULT 'VND',
    "Notes" varchar(1000) NULL,
    "CreatedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "CompletedUtc" timestamptz NULL,
    CONSTRAINT "FK_PaymentTransactions_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentTransactions_Subscriptions_SubscriptionId"
        FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PaymentTransactions_TransactionCode"
    ON "PaymentTransactions" ("TransactionCode");

CREATE INDEX IF NOT EXISTS "IX_PaymentTransactions_UserId_CreatedUtc"
    ON "PaymentTransactions" ("UserId", "CreatedUtc");

CREATE INDEX IF NOT EXISTS "IX_PaymentTransactions_PaymentStatus_CreatedUtc"
    ON "PaymentTransactions" ("PaymentStatus", "CreatedUtc");

CREATE INDEX IF NOT EXISTS "IX_UserTours_PoiId_VisitedUtc"
    ON "UserTours" ("PoiId", "VisitedUtc");

INSERT INTO "SubscriptionPlans" (
    "PlanCode", "DisplayName", "Tier", "BillingPeriod", "FixedPrice", "Currency",
    "MaxAccessiblePoiCount", "MaxOwnerPoiCount", "MaxActivationRadiusMeters", "IsActive",
    "CreatedUtc", "UpdatedUtc", "CreatedByAdminUserId", "UpdatedByAdminUserId")
SELECT
    'FREE-MONTHLY', 'Free Monthly', 'free', 'monthly', 0, 'VND',
    15, 6, 150, true,
    NOW(), NOW(), u."Id", NULL
FROM "Users" u
WHERE u."Role" = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM "SubscriptionPlans" p
      WHERE p."Tier" = 'free' AND p."BillingPeriod" = 'monthly'
  )
LIMIT 1;

INSERT INTO "SubscriptionPlans" (
    "PlanCode", "DisplayName", "Tier", "BillingPeriod", "FixedPrice", "Currency",
    "MaxAccessiblePoiCount", "MaxOwnerPoiCount", "MaxActivationRadiusMeters", "IsActive",
    "CreatedUtc", "UpdatedUtc", "CreatedByAdminUserId", "UpdatedByAdminUserId")
SELECT
    'BASIC-MONTHLY', 'Basic Monthly', 'basic', 'monthly', 99000, 'VND',
    60, 25, 150, true,
    NOW(), NOW(), u."Id", NULL
FROM "Users" u
WHERE u."Role" = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM "SubscriptionPlans" p
      WHERE p."Tier" = 'basic' AND p."BillingPeriod" = 'monthly'
  )
LIMIT 1;

INSERT INTO "SubscriptionPlans" (
    "PlanCode", "DisplayName", "Tier", "BillingPeriod", "FixedPrice", "Currency",
    "MaxAccessiblePoiCount", "MaxOwnerPoiCount", "MaxActivationRadiusMeters", "IsActive",
    "CreatedUtc", "UpdatedUtc", "CreatedByAdminUserId", "UpdatedByAdminUserId")
SELECT
    'PREMIUM-MONTHLY', 'Premium Monthly', 'premium', 'monthly', 299000, 'VND',
    NULL, NULL, 500, true,
    NOW(), NOW(), u."Id", NULL
FROM "Users" u
WHERE u."Role" = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM "SubscriptionPlans" p
      WHERE p."Tier" = 'premium' AND p."BillingPeriod" = 'monthly'
  )
LIMIT 1;

COMMIT;
