BEGIN;

CREATE TABLE IF NOT EXISTS "TourList" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TourCode" varchar(50) NOT NULL,
    "TourName" varchar(150) NULL,
    "OwnerUserId" integer NULL,
    "IsPublic" boolean NOT NULL DEFAULT false,
    "PoiId" varchar(20) NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedUtc" timestamptz NOT NULL,
    CONSTRAINT "FK_TourList_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TourList_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

ALTER TABLE "TourList" ADD COLUMN IF NOT EXISTS "TourName" varchar(150);
ALTER TABLE "TourList" ADD COLUMN IF NOT EXISTS "OwnerUserId" integer;
ALTER TABLE "TourList" ADD COLUMN IF NOT EXISTS "IsPublic" boolean NOT NULL DEFAULT false;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_TourList_Users_OwnerUserId'
    ) THEN
        ALTER TABLE "TourList"
        ADD CONSTRAINT "FK_TourList_Users_OwnerUserId"
        FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_TourList_TourCode_SortOrder"
    ON "TourList" ("TourCode", "SortOrder");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_TourList_TourCode_PoiId"
    ON "TourList" ("TourCode", "PoiId");

CREATE INDEX IF NOT EXISTS "IX_TourList_IsPublic"
        ON "TourList" ("IsPublic");

CREATE INDEX IF NOT EXISTS "IX_TourList_OwnerUserId_IsPublic"
        ON "TourList" ("OwnerUserId", "IsPublic");

UPDATE "TourList"
SET "IsPublic" = true
WHERE "IsPublic" = false
    AND "TourCode" LIKE 'PUB\_%' ESCAPE '\';

UPDATE "TourList" t
SET "OwnerUserId" = parsed."OwnerId"
FROM (
        SELECT
                "Id",
                split_part("TourCode", '_', 2)::integer AS "OwnerId"
        FROM "TourList"
        WHERE "OwnerUserId" IS NULL
            AND "TourCode" LIKE 'USR\_%' ESCAPE '\'
            AND split_part("TourCode", '_', 2) ~ '^[0-9]+$'
) parsed
WHERE t."Id" = parsed."Id";

UPDATE "TourList" t
SET "TourName" = parsed."NamePart"
FROM (
        SELECT
                "Id",
                NULLIF(REGEXP_REPLACE(split_part("TourCode", '_', 3), '[^A-Z0-9_]', '', 'g'), '') AS "NamePart"
        FROM "TourList"
        WHERE "TourName" IS NULL
            AND "TourCode" LIKE 'USR\_%' ESCAPE '\'
) parsed
WHERE t."Id" = parsed."Id"
    AND parsed."NamePart" IS NOT NULL;

UPDATE "TourList"
SET "TourName" = REGEXP_REPLACE(split_part("TourCode", '_', 2), '[^A-Z0-9_]', '', 'g')
WHERE "TourName" IS NULL
    AND "TourCode" LIKE 'PUB\_%' ESCAPE '\';

INSERT INTO "TourList" ("TourCode", "TourName", "OwnerUserId", "IsPublic", "PoiId", "SortOrder", "CreatedUtc")
SELECT 'DEFAULT', 'DEFAULT', NULL, true, p."Id", ROW_NUMBER() OVER (ORDER BY p."Priority", p."Id"), NOW()
FROM "POIs" p
WHERE p."ApprovalStatus" = 'approved'
    AND NOT EXISTS (
            SELECT 1
            FROM "TourList" t
            WHERE t."TourCode" = 'DEFAULT'
    )
ORDER BY p."Priority", p."Id"
LIMIT 12;

COMMIT;