-- Tạo database (chạy bằng tài khoản có quyền tạo DB)
CREATE DATABASE food_map;

-- Kết nối vào database vừa tạo
\c food_map;

CREATE TABLE IF NOT EXISTS "Languages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LanguageCode" varchar(10) NOT NULL,
    "LanguageName" varchar(100) NOT NULL,
    CONSTRAINT "UX_Languages_LanguageCode" UNIQUE ("LanguageCode")
);

CREATE TABLE IF NOT EXISTS "POIs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "ActivationRadius" integer NOT NULL,
    "Priority" integer NOT NULL,
    "QRCodeId" varchar(100) NULL
);

CREATE TABLE IF NOT EXISTS "POITranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PoiId" integer NOT NULL,
    "LanguageId" integer NOT NULL,
    "LocationName" varchar(200) NOT NULL,
    "Description" text NOT NULL,
    "ImageUrl" varchar(500) NOT NULL,
    "AudioFileUrl" varchar(500) NOT NULL,
    "TtsScript" text NOT NULL,
    CONSTRAINT "FK_POITranslations_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_POITranslations_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_POITranslations_PoiId_LanguageId" UNIQUE ("PoiId", "LanguageId")
);

CREATE TABLE IF NOT EXISTS "MediaAssets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PoiTranslationId" integer NOT NULL,
    "AssetType" varchar(20) NOT NULL,
    "RemoteUrl" varchar(500) NOT NULL,
    "LocalPath" varchar(500) NOT NULL,
    "FileName" varchar(200) NOT NULL,
    "ContentHash" varchar(128) NULL,
    "IsDownloaded" boolean NOT NULL,
    "LastDownloadedUtc" timestamptz NULL,
    CONSTRAINT "FK_MediaAssets_POITranslations_PoiTranslationId" FOREIGN KEY ("PoiTranslationId") REFERENCES "POITranslations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UX_MediaAssets_PoiTranslationId_AssetType" UNIQUE ("PoiTranslationId", "AssetType")
);

CREATE TABLE IF NOT EXISTS "SyncHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SyncType" varchar(50) NOT NULL,
    "StartedUtc" timestamptz NOT NULL,
    "CompletedUtc" timestamptz NULL,
    "IsSuccess" boolean NOT NULL,
    "ErrorMessage" varchar(1000) NULL
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName" varchar(100) NOT NULL,
    "PasswordHash" varchar(256) NOT NULL,
    "DisplayName" varchar(150) NOT NULL,
    "CreatedUtc" timestamptz NOT NULL,
    CONSTRAINT "UX_Users_UserName" UNIQUE ("UserName")
);

CREATE TABLE IF NOT EXISTS "UserFavorites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "PoiId" integer NOT NULL,
    "CreatedUtc" timestamptz NOT NULL,
    CONSTRAINT "FK_UserFavorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserFavorites_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UX_UserFavorites_UserId_PoiId" UNIQUE ("UserId", "PoiId")
);

CREATE TABLE IF NOT EXISTS "UserTours" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "PoiId" integer NOT NULL,
    "LanguageCode" varchar(10) NOT NULL,
    "TriggerType" varchar(30) NOT NULL,
    "VisitedUtc" timestamptz NOT NULL,
    CONSTRAINT "FK_UserTours_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserTours_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserTours_UserId_VisitedUtc" ON "UserTours" ("UserId", "VisitedUtc");

-- Tài khoản demo (mật khẩu gốc: 123456, lưu dạng SHA256 HEX)
INSERT INTO "Users" ("UserName", "PasswordHash", "DisplayName", "CreatedUtc")
SELECT 'demo', '8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92', 'Demo User', NOW()
WHERE NOT EXISTS (SELECT 1 FROM "Users" WHERE "UserName" = 'demo');
