-- PostgreSQL bootstrap script for FOOD_MAP Phase 2 schema.
-- Usage:
-- 1) psql -h <host> -p <port> -U <user> -f postgresql-init.sql
-- 2) Then run migration/seed script: psql ... -d food_map -f 04-phase2-schema-update.sql

CREATE DATABASE food_map;
\c food_map;

BEGIN;

CREATE TABLE IF NOT EXISTS "Languages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LanguageCode" varchar(10) NOT NULL,
    "LanguageName" varchar(100) NOT NULL,
    CONSTRAINT "UX_Languages_LanguageCode" UNIQUE ("LanguageCode")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName" varchar(100) NOT NULL,
    "PasswordHash" varchar(256) NOT NULL,
    "DisplayName" varchar(150) NOT NULL,
    "Role" varchar(20) NOT NULL DEFAULT 'user',
    "OwnerIdentificationCode" varchar(30) NULL,
    "OwnerApprovedUtc" timestamptz NULL,
    "CreatedUtc" timestamptz NOT NULL,
    CONSTRAINT "UX_Users_UserName" UNIQUE ("UserName")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_OwnerIdentificationCode"
    ON "Users" ("OwnerIdentificationCode")
    WHERE "OwnerIdentificationCode" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "POIs" (
    "Id" varchar(20) PRIMARY KEY,
    "Type" varchar(20) NOT NULL DEFAULT 'visit',
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "ActivationRadius" integer NOT NULL,
    "Priority" integer NOT NULL,
    "ApprovalStatus" varchar(20) NOT NULL DEFAULT 'pending',
    "SubmittedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "ReviewedUtc" timestamptz NULL,
    "OwnerId" integer NULL,
    "ReviewedByAdminUserId" integer NULL,
    "QRCodeId" varchar(100) NULL,
    CONSTRAINT "FK_POIs_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_POIs_Users_ReviewedByAdminUserId" FOREIGN KEY ("ReviewedByAdminUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_POIs_Type_ApprovalStatus" ON "POIs" ("Type", "ApprovalStatus");
CREATE INDEX IF NOT EXISTS "IX_POIs_OwnerId" ON "POIs" ("OwnerId");

CREATE TABLE IF NOT EXISTS "POITranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PoiId" varchar(20) NOT NULL,
    "LanguageId" integer NOT NULL,
    "LocationName" varchar(200) NOT NULL,
    "Description" text NOT NULL,
    "ImageUrl" varchar(500) NOT NULL,
    "AudioFileUrl" varchar(500) NOT NULL,
    "TtsScript" text NOT NULL,
    "RichContentHtml" text NOT NULL DEFAULT '',
    CONSTRAINT "FK_POITranslations_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_POITranslations_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UX_POITranslations_PoiId_LanguageId" UNIQUE ("PoiId", "LanguageId")
);

CREATE TABLE IF NOT EXISTS "MediaAssets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PoiTranslationId" integer NOT NULL,
    "AssetType" varchar(20) NOT NULL,
    "RemoteUrl" varchar(500) NOT NULL,
    "LocalPath" varchar(500) NOT NULL,
    "FileName" varchar(200) NOT NULL,
    "ContentHash" varchar(128) NULL,
    "IsDownloaded" boolean NOT NULL,
    "LastDownloadedUtc" timestamptz NULL,
    CONSTRAINT "FK_MediaAssets_POITranslations_PoiTranslationId" FOREIGN KEY ("PoiTranslationId") REFERENCES "POITranslations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UX_MediaAssets_PoiTranslationId_AssetType" UNIQUE ("PoiTranslationId", "AssetType")
);

CREATE TABLE IF NOT EXISTS "SyncHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SyncType" varchar(50) NOT NULL,
    "StartedUtc" timestamptz NOT NULL,
    "CompletedUtc" timestamptz NULL,
    "IsSuccess" boolean NOT NULL,
    "ErrorMessage" varchar(1000) NULL
);

CREATE TABLE IF NOT EXISTS "OwnerRegistrationRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "BusinessName" varchar(200) NOT NULL,
    "BusinessAddress" varchar(300) NOT NULL,
    "ContactPhone" varchar(30) NOT NULL,
    "Notes" varchar(1000) NULL,
    "Status" varchar(20) NOT NULL DEFAULT 'pending',
    "RequestedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "ReviewedUtc" timestamptz NULL,
    "ReviewedByAdminUserId" integer NULL,
    "RejectionReason" varchar(500) NULL,
    "ApprovedOwnerCode" varchar(30) NULL,
    CONSTRAINT "FK_OwnerRegistrationRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OwnerRegistrationRequests_Users_ReviewedByAdminUserId" FOREIGN KEY ("ReviewedByAdminUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_OwnerRegistrationRequests_UserId_Status_RequestedUtc"
    ON "OwnerRegistrationRequests" ("UserId", "Status", "RequestedUtc");

CREATE TABLE IF NOT EXISTS "LanguageOwnershipRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OwnerUserId" integer NOT NULL,
    "LanguageId" integer NOT NULL,
    "Status" varchar(20) NOT NULL DEFAULT 'pending',
    "RequestedUtc" timestamptz NOT NULL DEFAULT NOW(),
    "ReviewedUtc" timestamptz NULL,
    "ReviewedByAdminUserId" integer NULL,
    "RejectionReason" varchar(500) NULL,
    CONSTRAINT "FK_LanguageOwnershipRequests_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LanguageOwnershipRequests_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LanguageOwnershipRequests_Users_ReviewedByAdminUserId" FOREIGN KEY ("ReviewedByAdminUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_LanguageOwnershipRequests_OwnerUserId_LanguageId_Status_RequestedUtc"
    ON "LanguageOwnershipRequests" ("OwnerUserId", "LanguageId", "Status", "RequestedUtc");

CREATE TABLE IF NOT EXISTS "FoodItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PoiId" varchar(20) NOT NULL,
    "OwnerId" integer NULL,
    "Name" varchar(200) NOT NULL,
    "Description" varchar(1000) NULL,
    "Price" numeric(12,2) NOT NULL DEFAULT 0,
    "Currency" varchar(10) NOT NULL DEFAULT 'VND',
    "IsAvailable" boolean NOT NULL DEFAULT true,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "CreatedUtc" timestamptz NOT NULL,
    "UpdatedUtc" timestamptz NOT NULL,
    CONSTRAINT "FK_FoodItems_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FoodItems_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_FoodItems_PoiId_DisplayOrder" ON "FoodItems" ("PoiId", "DisplayOrder");

CREATE TABLE IF NOT EXISTS "UserFavorites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "PoiId" varchar(20) NOT NULL,
    "CreatedUtc" timestamptz NOT NULL,
    CONSTRAINT "FK_UserFavorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserFavorites_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UX_UserFavorites_UserId_PoiId" UNIQUE ("UserId", "PoiId")
);

CREATE TABLE IF NOT EXISTS "UserTours" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "PoiId" varchar(20) NOT NULL,
    "LanguageCode" varchar(10) NOT NULL,
    "TriggerType" varchar(30) NOT NULL,
    "VisitedUtc" timestamptz NOT NULL,
    CONSTRAINT "FK_UserTours_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserTours_POIs_PoiId" FOREIGN KEY ("PoiId") REFERENCES "POIs" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserTours_UserId_VisitedUtc" ON "UserTours" ("UserId", "VisitedUtc");

COMMIT;
